#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

find src \( -path src/main/java/io/teak/sdk/shortcutbadger -o -path src/main/java/io/teak/sdk/json \) -prune -o -type f -name "*.java" -print | xargs clang-format -style=file -i
