version: 2.1

orbs:
  teak: teak/sdk-utils@1
  buildomat: teak/buildomat@0.1
  aws-cli: circleci/aws-cli@5.4.0

jobs:
  build:
    docker:
      - image: cimg/android:2023.07
        environment:
          ANDROID_HOME=/opt/android/sdk
    steps:
      - checkout
      - run:
          name: Check for any usage of the org.json.* namespace
          command: ./org_json_check
      - restore_cache:
          key: v0-{{ checksum "build.gradle" }}-{{ checksum  "test_app/build.gradle" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Sentry CLI
          command: curl -sL https://sentry.io/get-cli/ | bash
      - run:
          name: Fix 'sdk.dir' in 'local.properties'
          command: |
            echo 'sdk.dir=/opt/android/sdk' > local.properties
            echo 'sdk.dir=/opt/android/sdk' > test_app/local.properties
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v0-{{ checksum "build.gradle" }}-{{ checksum  "test_app/build.gradle" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Build Teak SDK
          command: ./gradlew assemble
      - run:
          name: Compute Checksum
          command: |
            sha512sum build/outputs/aar/teak-release.aar > teak-release.sha512
            sha256sum build/outputs/aar/teak-release.aar > teak-release.sha256
      - persist_to_workspace:
          root: .
          paths:
            - build/outputs/aar/teak-release.aar
            - teak-release.sha512
            - teak-release.sha256
      - sentry_persist_proguard
      - sentry_upload_proguard:
          sentry_cli_args: --no-upload
      - store_artifacts:
          path: build/outputs/mapping/release/mapping.txt
          destination: mapping.txt
      - run:
          name: Make sure we're not using Executors or Threads
          command: ./check_thread_use
      - run:
          name: Run Teak SDK Unit Tests
          command: (cd test_app; ./gradlew test --continue)
      - store_test_results:
          path: test_app/app/build/test-results/

  tag_build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - teak/tag-promote

  deploy_versioned:
    docker:
      - image: cimg/base:current
        environment:
          ANDROID_HOME=/opt/android/sdk
    steps:
      - checkout
      - run: git fetch --tags
      - run:
          name: Install Sentry CLI
          command: curl -sL https://sentry.io/get-cli/ | bash
      - aws-cli/setup
      - attach_workspace:
          at: .
      - sentry_upload_proguard
      - buildomat/aws-oidc-assume
      - run:
          name: Upload SDK to S3
          command: |
            aws s3 cp build/outputs/aar/teak-release.aar s3://teak-build-artifacts/android/teak-$(git describe --tags --always).aar --acl public-read
            aws s3 cp teak-release.sha512 s3://teak-build-artifacts/android/teak-$(git describe --tags --always).sha512 --acl public-read
            aws s3 cp teak-release.sha256 s3://teak-build-artifacts/android/teak-$(git describe --tags --always).sha256 --acl public-read

  deploy_latest:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: git fetch --tags
      - run:
          name: Install Sentry CLI
          command: curl -sL https://sentry.io/get-cli/ | bash
      - aws-cli/setup
      - attach_workspace:
          at: .
      - sentry_upload_proguard
      - buildomat/aws-oidc-assume
      - run:
          name: Upload SDK to S3
          command: |
            aws s3 cp build/outputs/aar/teak-release.aar s3://teak-build-artifacts/android/teak.aar --acl public-read
            aws s3 cp teak-release.sha256 s3://teak-build-artifacts/android/teak.sha256 --acl public-read
            aws s3 cp teak-release.sha512 s3://teak-build-artifacts/android/teak.sha512 --acl public-read

workflows:
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * 2-6"
          filters:
            branches:
              only:
                - develop
    jobs:
      - build:
          context:
            - Sentry

  un-tagged-build:
    jobs:
      - build:
          context:
            - Sentry
          filters:
            tags:
              ignore: /.*/
      - tag_build:
          requires:
            - build
          filters:
            tags:
              ignore: /.*/

  tagged-build:
    jobs:
      - build:
          context:
            - Sentry
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - deploy_versioned:
          context:
            - AWS-OIDC-Role
            - Sentry
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - deploy_latest:
          context:
            - AWS-OIDC-Role
            - Sentry
          requires:
            - hold
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/

commands:
  #
  # Persist ProGuard mappings to workspace
  #
  sentry_persist_proguard:
    description: "Persist ProGuard Mappings to Workspace"
    parameters:
      proguard_mapping:
        type: string
        default: "build/outputs/mapping/release/mapping.txt"
      sentry_uuid:
        type: string
        default: "build/intermediates/assets/release/sentry-debug-meta.properties"
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - << parameters.proguard_mapping >>
  #
  # Upload ProGuard mappings to Sentry
  #
  sentry_upload_proguard:
    description: "Upload ProGuard Mappings to Sentry"
    parameters:
      proguard_mapping:
        type: string
        default: "build/outputs/mapping/release/mapping.txt"
      sentry_cli_args:
        type: string
        default: ""
    steps:
      - run:
          name: Upload ProGuard Mappings to Sentry
          command: |
            sentry-cli --version
            sentry-cli upload-proguard -p "${CIRCLE_PROJECT_REPONAME}-sdk" --require-one << parameters.proguard_mapping >> << parameters.sentry_cli_args >>
