= Working with Teak on Android

== Identify User

This tells Teak how the user should be referenced in the Teak system.

All Teak events will be delayed until ``identifyUser`` is called.

doxygen2adoc:Teak.identifyUser(String,UserConfiguration)[]

IMPORTANT: This should be the same way that you identify the user in your system, so that when you export data from Teak, it will be easy for you to associate with your own data.

== User Attributes

Teak allows you to add a limited number of attributes to users. A maximum of 16 string and 16 numeric attributes can be used.

doxygen2adoc:Teak.setNumericAttribute(String,double)[]

doxygen2adoc:Teak.setStringAttribute(String,String)[]

== Notification Permissions

On Android 13 (API level 33) and newer, you must ask the player before you can send them push notifications. On older versions, permission is granted automatically.

The xref:quickstart/required-code.adoc[quickstart] requests permission at launch to get you up and running. In production, ask at a moment that makes sense for your game; being strategic about when you ask improves your opt-in rates.

doxygen2adoc:Teak.requestNotificationPermissions()[]

Unlike some platforms, this call does not take a callback. To find out whether notifications are currently enabled, check the status:

doxygen2adoc:Teak.getNotificationStatus()[]

It returns one of `Teak.TEAK_NOTIFICATIONS_ENABLED`, `Teak.TEAK_NOTIFICATIONS_DISABLED`, or `Teak.TEAK_NOTIFICATIONS_UNKNOWN`.

=== Prompting a Player to Re-enable Notifications

If a player has turned notifications off, you can no longer prompt them from within the app. Instead, you can send them to the system settings, where they can turn notifications back on.

doxygen2adoc:Teak.canOpenNotificationSettings()[]

doxygen2adoc:Teak.openNotificationSettings()[]

== Deep Links

Teak can open your game from a URL, whether the link comes from a notification or from a link you created on the Teak dashboard. To enable this, register Teak's URL schemes in your Android manifest.

Add the following to the `<activity>` section of your `AndroidManifest.xml`:

.AndroidManifest.xml
[source,xml]
----
<intent-filter android:autoVerify="true">
  <action android:name="android.intent.action.VIEW" />
  <category android:name="android.intent.category.DEFAULT" />
  <category android:name="android.intent.category.BROWSABLE" />
  <data android:scheme="http" android:host="YOUR_SHORTLINK_DOMAIN.jckpt.me" />
  <data android:scheme="https" android:host="YOUR_SHORTLINK_DOMAIN.jckpt.me" />
</intent-filter>
<intent-filter>
  <action android:name="android.intent.action.VIEW" />
  <category android:name="android.intent.category.DEFAULT" />
  <category android:name="android.intent.category.BROWSABLE" />
  <data android:scheme="teakYOUR_TEAK_APP_ID" android:host="*" />
</intent-filter>
----

NOTE: Replace `YOUR_TEAK_APP_ID` with your Teak App Id and `YOUR_SHORTLINK_DOMAIN` with your Teak ShortLink Domain. Both are found in the Settings for your app on the Teak dashboard.

This tells Android to look for deep link URLs created by Teak.

== Subscribing to Events

Teak uses https://github.com/greenrobot/EventBus[EventBus] to send events to your game.

=== Register an Object to Handle Events

You can register any object to handle events posted by Teak. A quick way to get started is to register your main activity as a handler:

.Registering an event handler
[source,java]
----
import androidx.appcompat.app.AppCompatActivity;

import org.greenrobot.eventbus.EventBus;
import org.greenrobot.eventbus.Subscribe;

public class MainActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Register with EventBus
        EventBus.getDefault().register(this);
}
----

To receive events, declare methods with the `@Subscribe` annotation that take the type of event the method should handle.

=== Events

<<Teak.NotificationEvent>>:: A notification has been received.

<<Teak.RewardClaimEvent>>:: A reward claim has been processed. See <<Rewards>>.

<<Teak.LaunchFromLinkEvent>>:: The app was launched from a URL created on the Teak dashboard.

<<Teak.PostLaunchSummaryEvent>>:: Attribution data for the launch is available. See <<Session Attribution>>.

<<Teak.UserDataEvent>>:: Data about the user has become available, or has been updated.

== Rewards

Teak notifications and links can grant rewards to your players. When a player opens your game from a rewarded notification or link, Teak validates the claim with the server and posts a <<Teak.RewardClaimEvent>> with the result.

Subscribe to it the same way as any other event (see <<Subscribing to Events>>), then grant the reward in your game when the claim succeeds.

.Handling a Reward Claim
[source,java]
----
@Subscribe
public void onRewardClaim(Teak.RewardClaimEvent event) {
  TeakNotification.Reward rewardInfo = event.reward;
  String rewardId = rewardInfo.json.getString("teakRewardId");
  switch(rewardInfo.status) {
    case TeakNotification.Reward.GRANT_REWARD: {
      Map<String, Object> reward = rewardInfo.json.getJSONObject("reward").toMap();
      Log.d("TeakExample.Reward", "Reward with id " + rewardId + "Granted! " + reward.toString());
    } break;
    case TeakNotification.Reward.ALREADY_CLICKED: {
      Log.d("TeakExample.Reward", "You already claimed this reward!");
    } break;
    case TeakNotification.Reward.EXPIRED: {
      Log.d("TeakExample.Reward", "The reward has expired");
    } break;
    case TeakNotification.Reward.TOO_MANY_CLICKS: {
      Log.d("TeakExample.Reward", "Too many other players already claimed this reward");
    } break;
    case TeakNotification.Reward.EXCEED_MAX_CLICKS_FOR_DAY: {
      Log.d("TeakExample.Reward", "You've already claimed too many rewards today");
    } break;
    default: {
      Log.d("TeakExample.Reward", "The reward was rejected for a different reason: " + rewardInfo.json.getString("status"));
    }
  }
}
----

The `status` field reports the outcome of the claim:

[cols="1,3", stripes="even"]
|===
| Status | Meaning

| `GRANT_REWARD`
| The reward was granted. Apply it in your game.

| `SELF_CLICK`
| The player clicked their own shared link, so no reward was granted.

| `ALREADY_CLICKED`
| The player already claimed this reward.

| `TOO_MANY_CLICKS`
| The reward's click limit has been reached.

| `EXCEED_MAX_CLICKS_FOR_DAY`
| The player has already claimed the maximum number of rewards for the day.

| `EXPIRED`
| The reward has expired.

| `INVALID_POST`
| The claim was invalid.
|===

== Session Attribution

Each time your game launches, Teak posts a <<Teak.PostLaunchSummaryEvent>> with all the attribution data it has for that launch. This fires after you call `identifyUser`, and is primarily intended to help you report session attribution to other analytics systems.

Subscribe to it like any other event (see <<Subscribing to Events>>). The event's `launchData` is a <<Teak.LaunchData>>. When the launch is attributed to a Teak source, it is a <<Teak.AttributedLaunchData>> carrying the channel, creative, schedule, reward, and deep link details.

.Example Post-Launch Summary Handler
[source,java]
----
@Subscribe
public void onPostLaunchSummary(Teak.PostLaunchSummaryEvent event) {
  Teak.LaunchData launchData = event.launchData;
  if (launchData instanceof Teak.AttributedLaunchData) {
    Teak.AttributedLaunchData attributed = (Teak.AttributedLaunchData) launchData;
    Log.d("Teak.Attribution", "Launch attributed to channel: " + attributed.channelName);
    Log.d("Teak.Attribution", "From creative: " + attributed.creativeName);
    Log.d("Teak.Attribution", "Rewarded: " + attributed.isIncentivized());
  } else {
    Log.d("Teak.Attribution", "Launch was not attributed to a Teak source.");
  }
}
----
