apply plugin: 'com.android.application'

android {
    compileSdk 35

    defaultConfig {
        applicationId "io.teak.app.unity.dev"
        minSdkVersion 21
        targetSdk 35
        versionCode 1
        versionName "1.0"

        manifestPlaceholders = [
                teakShortDomain:"teak-dev.freechips.link",
                teakAppId:"613659812345256"
        ]
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        aidl true

    }
    namespace 'io.teak.app.java.dev'
}

gradle.projectsEvaluated {
    if (android.defaultConfig.targetSdkVersion.apiLevel < android.compileSdkVersion.split(/\-/)[1] as Integer) {
        throw new GradleException('targetSdkVersion is less than compileSdkVersion')
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.13.2'

    implementation 'androidx.core:core:1.6+'
    implementation 'androidx.work:work-runtime:2.7+'

    implementation 'androidx.appcompat:appcompat:1.3.1'
    implementation 'com.google.firebase:firebase-messaging:24.0.0'
    implementation 'org.greenrobot:eventbus:3.3.1'
    implementation "com.android.billingclient:billing:5.0.0"

    implementation project(path: ':teak')
}

apply plugin: 'com.google.gms.google-services'
